name: Spellcheck
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spellcheck
        uses: redis-stack/github-actions/spellcheck@6-0-1
        env:
          DICTIONARY: wordlist
          DOCS_DIRECTORY: .
          CONFIGURATION_FILE: .spellcheck.yml
          COMMANDS_FILES: commands.json
